config/routes.rb
SunwooBlog::Application.routes.draw do
  root to: 'posts#index'

  devise_for :users

  resources :posts
  resources :book_reviews
  resources :subscribers

  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  get '/projects' => 'pages#projects', as: :projects

  #tags
  get '/tags/:tag' => 'posts#index', as: :tag
end

app/models/book_review.rb
class BookReview < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  before_save :generate_body_html

  has_attached_file :image

  def generate_body_html
    return if self.review_text.blank?
    logger.debug "generate_body_html has been called".green
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(:hard_wrap => true),
      :no_intra_emphasis => true,
      :autolink => true,
      :fenced_code_blocks => true)

    self.body_html = Redcarpet::Render::SmartyPants.render(
      SyntaxHighlighter.new(
        markdown.render(self.review_text)
      ).to_s
    )
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged]
  acts_as_taggable

  before_save :generate_body_html

  has_attached_file :image, styles: { large: "1555×1037" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  def generate_body_html
    return if self.content.blank?
    logger.debug "generate_body_html has been called".green
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML.new(:hard_wrap => true),
      :no_intra_emphasis => true,
      :autolink => true,
      :fenced_code_blocks => true)

    self.body_html = Redcarpet::Render::SmartyPants.render(
      SyntaxHighlighter.new(
        markdown.render(self.content)
      ).to_s
    )
  end

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates_presence_of :email
  validates :email, email: true
end

app/models/syntax_highlighter.rb
require 'net/http'
class SyntaxHighlighter
  PYGMENTS_URI = 'http://pygments.simplabs.com/'
  attr_accessor :doc

  def initialize(html)
    self.doc = Nokogiri::HTML(html)
    doc.search("pre > code[class]").each do |code|
      request = Net::HTTP.post_form(URI.parse(PYGMENTS_URI),
        {
          'lang' => code[:class],
          'code' => code.text.rstrip
        }
      )
      code.parent.replace request.body
    end
  end

  def to_s
    doc.search("//body").children.to_s
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  def new
    @book_review = BookReview.new
  end

  def create
    @book_review = BookReview.new(book_review_params)
    if @book_review.save
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @book_review = BookReview.friendly.find(params[:id])
  end

  def edit
    @book_review = BookReview.friendly.find(params[:id])
  end

  def update
    @book_review = BookReview.friendly.find(params[:id])
    if @book_review.update(book_review_params)
      redirect_to root_url
    else
      render :edit
    end
  end

  def book_review_params
    params.require(:book_review).permit(:name, :subtitle, :review_text, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
  end

  def projects
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :authenticate_correct_user!, :except => [:index, :show]

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order("created_at DESC")
    else
      @posts = Post.all.order("created_at DESC")
    end
    @book_reviews = BookReview.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    if post.save
      puts "Saved!"
    else
      puts "Not saved!"
    end
    redirect_to root_url
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    post = Post.friendly.find(params[:id])
    post.update_attributes!(post_params)
    redirect_to post_path(params[:id])
  end

  def destroy
    post = Post.friendly.find(params[:id])
    post.destroy!
    redirect_to root_url
  end

  def show
    @post = Post.friendly.find(params[:id])
    @next_post = Post.find(@post.next_post.to_i) if @post.next_post
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :body_html, :image, :short, :tag_list, :next_post) if params[:post]
    end

    def authenticate_correct_user!
      redirect_to posts_path if current_user.email.downcase != "yangsunwoo@gmail.com"
    end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def create
    subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if subscriber.save
        SubscriberMailer.subscribed_notification(subscriber.email).deliver!
        format.js { render layout: false }
      else
        redirect_to root_url
      end
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:email, :source)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/book_reviews/edit.html.erb
<div class="col-md-12">

  <%= form_for @book_review, html: { multipart: true }, class: "form-control" do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control"  %><br>

    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle, class: "form-control" %>
    <br><br>

    <%= f.label :review_text %><br>
    <%= f.text_area :review_text, row: "12", class: "form-control"  %>
    <br><br>

    <%= f.label :image %><br>
    <%= f.file_field :image %><br>

    <% if @book_review.image %>
      <div id="book-image">
        <%= image_tag @book_review.image %>
      </div>
    <% end %>

    <br><br>
    
    <%= f.submit "Create Book Review", class:"btn btn-lg" %>

  <% end %>

</div>

app/views/book_reviews/new.html.erb
<div class="row">
  <div class="col-md-12">

    <%= form_for @book_review, html: { multipart: true } do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, size:"59" %><br>

      <%= f.label :subtitle %><br>
      <%= f.text_field :subtitle, :cols => "141", :rows => "20" %>
      <br><br>

      <%= f.label :review_text %><br>
      <%= f.text_area :review_text, :cols => "141", :rows => "20" %>
      <br><br>

      <%= f.label :image %><br>
      <%= f.file_field :image %><br>
      
      <%= f.submit "Create Book Review", class:"btn btn-lg" %>
    <% end %>

  </div>
</div>

app/views/book_reviews/show.html.erb
<span class="menu-trigger writer-icon animated fadeInDown">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
</span>

<% if @book_review.image.url != "/images/original/missing.png" %>
  <div class="hero-image img-responsive" style="background: url(<%= @book_review.image.url %>); background-position: center;">

    <!-- if the user has javascript disabled they can still use the menu -->
    <noscript>
      <div class="no-js-menu">
        <ul>
          <li><i class="entypo-home"></i><a href="/">Home</a></li>
          <li><i class="entypo-chart-area"></i><a href="dashboard.html">Stats</a></li>
        </ul>
      </div>
    </noscript>
    <!-- end no script -->

  </div>
<% end %>

<div class="container">
    <div class="row">

    <div id="menu">
        <ul>
            <li><i class="entypo-home"></i><a href="/">Home</a></li>
        </ul>
    </div>

    <div class="col-xs-12 main-content single-content">
        <p class="meta">
            <i class="entypo-bookmark"></i> <%= (@book_review.review_text.split.size / 200.0).ceil %> minutes to read
        </p>
        <h1><%= @book_review.name %></h1>

        <p><%=raw @book_review.body_html %></p>

    </div><!-- main-content/col -->


    </div> <!--/row -->

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    - if @post
      %title
        = @post.title
        | Sunwoo Yang
    - else
      %title Ideas to Customers | Sunwoo Yang
    - if @post
      :javascript
        (function(h,o,t,j,a,r){
          h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
          h._hjSettings={hjid:213213,hjsv:5};
          a=o.getElementsByTagName('head')[0];
          r=o.createElement('script');r.async=1;
          r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
          a.appendChild(r);
        })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
      %script{ src: "//my.hellobar.com/c3af3f4b4041182fccc123e2a7babd1276a5803e.js", type: "text/javascript", charset: "utf-8", async: "async" }
      %script{ type: "text/javascript", src: "//newsharecounts.s3-us-west-2.amazonaws.com/nsc.js" }
      :javascript
        window.newShareCountsAuto="smart";
    %script{ :src => "//load.sumome.com/", :data => { "sumo-site-id" => "7ee7b068ed4841c86d889e8bbdc978047091531355f4226434ddedfbdbf1df59" }, :async => "async" }
    = stylesheet_link_tag    "application", media: "all"
    %link{ rel: 'stylesheet', type: 'text/css', href: '/assets/animate.css' }
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{ :name => "google-site-verification", :content => "pZYi2NDh8MorfdpuP383CvS-fe8fFOnBRp9L8UfkgII" }/
    %link{:href => "favicon.ico", :rel => "shortcut icon"}/
    / Fonts
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700italic,800,800italic,700,600italic", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Merriweather", :rel => "stylesheet"}/
    %meta{ name: "google-site-verification", content: "vPOjeAcHdaY7gZPoud_XgqSeSuS5wTxsANHvgi3LNIQ" }
    - if @post
      %meta{ name: "twitter:card", content: "summary_large_image" }
      %meta{ name: "twitter:site", content: "@sunwooz" }
      %meta{ name: "twitter:creator", content: "@sunwooz" }
      %meta{ name: "twitter:title", content: "#{@post.title}" }
      %meta{ name: "twitter:description", content: "#{@post.short}"}
      %meta{ name: "twitter:image", content: "#{@post.image.url}" }
      %meta{ name: "og:image", content: "#{@post.image.url}" }
    / HTML5 shiv for IE8 support
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  %body
    .loading
    #header
      .top
        .search
          %form{:role => "form"}
            .form-group.has-feedback
              %input.form-control.input-sm{:placeholder => "Search..", :type => "text"}/
              %i.form-control-feedback.fa.fa-search
        %a.brand{:href => "/"}
          %span Sunwoo
        .slogan 
          Blog on 
          %span.tag #software, 
          %span.tag #entrepreneurship 
          &
          %span.tag #travel
      %nav.navbar.navbar-ada{:role => "navigation"}
        .navbar-header
          %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #navbar-collapse-1.collapse.navbar-collapse.navbar-ex1-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Home', root_path
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Tags
                %span.caret
              %ul.dropdown-menu.active
                %li
                  = link_to 'all posts', posts_path
                - Post.tag_counts.order('name ASC').each do |tag|
                  %li
                    = link_to tag.name, tag_path(tag.name)
            %li
              = link_to 'About Me', about_path
            %li
              = link_to 'Side Projects', projects_path
            %li
              = link_to 'Contact', contact_path

    - if flash[:alert]
      %p.flash-error= flash[:alert]
    - if flash[:notice]
      %p.flash-notice= flash[:notice]
    = yield

    #footer
    #subscribe
      .container
        .form-inline
          .form-group
            %p Learn to develop and market products with me!
          .form-group
            = form_for(Subscriber.new) do |f|
              .input-group
                = f.text_field :email, class: 'form-control'
                %span.input-group-btn
                  = f.submit "Subscribe", class: 'btn'
    #links
      .container
        .col-sm-2
          %p.brand
            %span Sunwoo
        .col-sm-8
          %ul.list-inline
            %li
              %a{:href => "/"} Home
            %li
              %a{:href => "/about"} About
            %li
              %a{:href => "/contact"} Contact
        .col-md-2
          %ul.list-inline
            %li
              %a{:href => "#"}
                %i.fa.fa-facebook
            %li
              %a{:href => "#"}
                %i.fa.fa-twitter
            %li
              %a{:href => "#"}
                %i.fa.fa-instagram
  %a#scroll-to-top
    %i.fa.fa-angle-up

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48335587-1', 'sunwooyang.com');
  ga('send', 'pageview');

app/views/pages/about.haml
#single
  .container
    .post.single-post
      .caption
        .header
          %h1 
            About Sunwoo Yang
        %p
          I'm a software entrepreneur/developer currently living in NYC.  I started off working in various companies and now I'm pursuing a couple of my own product ideas.  This blog is meant to document my thoughts while I work towards profitability.

app/views/pages/about.html.erb
<h1>About Sunwoo Yang</h1>

<p>
  I started off learning Japanese by myself in High School. It was then that I realized that anything I wanted to learn, I can learn on my own.  I went to a university in New Jersey and also a University in Thailand. It wasn't long until I decided that college was not for me. I wanted to be able to determine my own academic goals, and not by some curriculum that had no idea what my aspirations were. I attended The Flatiron School in NYC to study ruby, then worked as a software engineer for a short few months.
</p>
<p>
  I'm currently living in Thailand, working on my humble goal of 'first product' and 'first customer'.  It's very early on in my journey, and I may not make it out successful on my first attempt. This blog was made to help others on their way and also to keep track of my progress.
</p>
<p>
  Don't hesitate to e-mail me at <b>yangsunwoo@gmail.com</b><br>
  <a target="_blank" href="https://github.com/sunwooz">Github</a><br>
  <a target="_blank" href="https://www.linkedin.com/in/sunwooz">Linkedin</a>
</p>

  
</p>

app/views/pages/contact.haml
#single
  .container
    .post.single-post
      .caption
        .header
          %h1 
            My Contact Info
        %a{ href: 'github.com/sunwooz', target: '_blank' } My Github
        %br
        %a{ href: 'https://www.linkedin.com/in/sunwooz', target: '_blank' } My LinkedIn

        %br
        %br
        
        %p
          You can contact me by email at: yangsunwoo@gmail.com
        %p
          Feel free to send a text or call me at 908-723-9994(USA)

app/views/pages/projects.haml
#posts.container
  %section.col-md-12.wow.fadeIn
    .post.big
      .row
        .col-md-6.media
          = image_tag("https://s3.amazonaws.com/sunwooyang-blog/post-pictures/Screen+Shot+2016-06-14+at+11.41.54+AM.png", class: 'img-responsive', alt: "VRMachine Gear VR Games")
        .col-md-6.caption
          %h1{ class: 'post-title' }=link_to "VRMachine GearVR Search Engine", "vrmachine.io", target: "_blank"
          %span.post-tag
            Made in 2016
          %p.post-description
            A search/filter engine to help GearVR enthusiasts find the best Gear VR game.

#posts.container
  %section.col-md-12.wow.fadeIn
    .post.big
      .row
        .col-md-6.media
          = image_tag("https://s3.amazonaws.com/sunwooyang-blog/post-pictures/Screen+Shot+2016-06-18+at+12.26.37+PM.png", class: 'img-responsive', alt: "GemifyJS: Easy way to turn your assets into ruby gems")
        .col-md-6.caption
          %h1{ class: 'post-title' }=link_to "GemifyJS", "gemify-js.herokuapp.com", target: "_blank"
          %span.post-tag
            Made in 2014
          %p.post-description
            A web application to easily turn image/css/js assets into ruby gems.

#posts.container
  %section.col-md-12.wow.fadeIn
    .post.big
      .row
        .col-md-6.media
          = image_tag("https://s3.amazonaws.com/sunwooyang-blog/post-pictures/hnjs", class: 'img-responsive')
        .col-md-6.caption
          %h1{ class: 'post-title' }=link_to "Hacker News Job Search", "http://production-hnjs.us-east-1.elasticbeanstalk.com/", target: "_blank"
          %span.post-tag
            Made in 2014
          %p.post-description
            A job search engine that scrapes everything from HackerNews.  There's a rails rake task being run by a cron job every hour to pull in the latest jobs. Made a quick custom search engine ontop of postgresql using vector search.  This was the first web app I made after joining Flatiron School.

            Uses Rails, Postgresql, AWS


#posts.container
  %section.col-md-12.wow.fadeIn
    .post.big
      .row
        .col-md-6.media
          = image_tag("http://clearwaterbeachassoc.com/wp-content/uploads/2016/01/Under-construction.png", class: 'img-responsive')
        .col-md-6.caption
          %h1{ class: 'post-title' } Under Construction
          %p.post-description
            I'm currently moving all of my projects from Heroku to AWS to save on costs and learn to deploy somewhere new. This page will be updated soon. By the way, I'm currently looking for a web development job in NYC. My contact information is under /contact

app/views/posts/_all_posts.haml
- @posts.each do |post|
  #posts.container
    %section.col-md-12.wow.fadeIn
      .post.big
        .row
          .col-md-6.media
            = link_to image_tag(post.image.url(:large), class: 'img-responsive'), post
          .col-md-6.caption
            %span.post-tag
              -post.tag_list.each do |tag|
                = link_to "#" + tag, tag_path(tag)

            = link_to post.title, post, class: 'post-title'
            %span.post-date= post.created_at.strftime("%A, %b %d")
            %p.post-description
              = raw post.short
              = link_to 'read more...', post
            - if current_user && current_user.email == 'yangsunwoo@gmail.com'
              = link_to 'Edit', edit_post_path(post)
              = link_to 'Destroy', post_path(post), method: :delete, confirm: 'Are you sure?'

app/views/posts/_form.haml
.row
  .col-md-12
    = form_for @post, html: { multipart: true } do |f|
      = f.label :title
      %br/
      = f.text_field :title, size: "59", cols: "140" , style: "padding:30px; font-size:30px; text-align: center; width: 100%;"
      %br/
      = f.label :short
      %br/
      = f.text_area :short
      %br/
      = f.label :tag_list, "Tags (separated by commas)"
      %br/
      = f.text_field :tag_list
      %br
      = f.label :next_post
      %br
      = f.text_field :next_post
      %br
      = f.label :content
      %br/
      = f.text_area :content, :rows => "20", style: "width: 80%; margin: 0 auto; font-size: 20px;"
      %br/
      %br/
      = f.label :image
      %br/
      = f.file_field :image
      %br/
      = f.submit "Post!", class:"btn btn-lg"

:javascript
  $(document).ready(function() {
    var postTagList = $('#post_tag_list')
    var tagListWithSpaces = postTagList.val()
    var replaced = tagListWithSpaces.replace(' ', ', ')
    postTagList.val(replaced)
  });
  

app/views/posts/edit.haml
= render "posts/form"

app/views/posts/index.haml
= render "posts/all_posts"

app/views/posts/new.haml
= render "posts/form"

app/views/posts/show.haml
#single
  .container
    .post.single-post
      .caption
        .header
          %span.post-tag
            - @post.tag_list.each do |tag|
              = link_to "#" + tag, tag_path(tag)
          %h1#single-post-title= @post.title
          %i{ style: "font-size: 1em;" }
            Written by Sunwoo Yang on
          %b
          %i{ style: "font-size: .7em;" }
            = @post.created_at.strftime("%A, %b %d")
        %p= raw @post.body_html
        = hidden_field_tag :post_id, @post.id

        - if @post.next_post
          #related-posts
            .row
              .col-xs-12
                %h2 Related Post
                = link_to @next_post.title, @next_post
          
        - if @post.tag_list.include?('coming-soon')

          #subscribe
            .form-inline
              %div
                %p Get notified when this post is ready!
              .form-group
                = form_for Subscriber.new, remote: true do |f|
                  .input-group
                    = f.hidden_field :source, value: @post.title
                    = f.text_field :email, class: 'form-control'
                    %span.input-group-btn
                      = f.submit "Subscribe", class: 'btn', onclick: "ga('send', 'event', 'Subscribe', 'Click', 'Subscribe');"
      
    .comments
      / START DISQUS
      #disqus_thread
      :javascript
        /* * * CONFIGURATION VARIABLES * * */
        var disqus_shortname = 'sunwooblog';
        
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
      %noscript
        Please enable JavaScript to view the
        %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments powered by Disqus.
      / END DISQUS

app/views/subscribers/create.js.erb
$('#subscribe').html("Thanks! We'll let you know when it's ready!")